/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.zcbl.malaka.rpc.common.inter;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class RpcResponse implements org.apache.thrift.TBase<RpcResponse, RpcResponse._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RpcResponse");

  private static final org.apache.thrift.protocol.TField PARAMTER_FIELD_DESC = new org.apache.thrift.protocol.TField("paramter", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RpcResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RpcResponseTupleSchemeFactory());
  }

  public Map<String,String> paramter; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PARAMTER((short)1, "paramter");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PARAMTER
          return PARAMTER;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PARAMTER, new org.apache.thrift.meta_data.FieldMetaData("paramter", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RpcResponse.class, metaDataMap);
  }

  public RpcResponse() {
  }

  public RpcResponse(
    Map<String,String> paramter)
  {
    this();
    this.paramter = paramter;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RpcResponse(RpcResponse other) {
    if (other.isSetParamter()) {
      Map<String,String> __this__paramter = new HashMap<String,String>();
      for (Map.Entry<String, String> other_element : other.paramter.entrySet()) {

        String other_element_key = other_element.getKey();
        String other_element_value = other_element.getValue();

        String __this__paramter_copy_key = other_element_key;

        String __this__paramter_copy_value = other_element_value;

        __this__paramter.put(__this__paramter_copy_key, __this__paramter_copy_value);
      }
      this.paramter = __this__paramter;
    }
  }

  public RpcResponse deepCopy() {
    return new RpcResponse(this);
  }

  @Override
  public void clear() {
    this.paramter = null;
  }

  public int getParamterSize() {
    return (this.paramter == null) ? 0 : this.paramter.size();
  }

  public void putToParamter(String key, String val) {
    if (this.paramter == null) {
      this.paramter = new HashMap<String,String>();
    }
    this.paramter.put(key, val);
  }

  public Map<String,String> getParamter() {
    return this.paramter;
  }

  public RpcResponse setParamter(Map<String,String> paramter) {
    this.paramter = paramter;
    return this;
  }

  public void unsetParamter() {
    this.paramter = null;
  }

  /** Returns true if field paramter is set (has been assigned a value) and false otherwise */
  public boolean isSetParamter() {
    return this.paramter != null;
  }

  public void setParamterIsSet(boolean value) {
    if (!value) {
      this.paramter = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PARAMTER:
      if (value == null) {
        unsetParamter();
      } else {
        setParamter((Map<String,String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PARAMTER:
      return getParamter();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PARAMTER:
      return isSetParamter();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RpcResponse)
      return this.equals((RpcResponse)that);
    return false;
  }

  public boolean equals(RpcResponse that) {
    if (that == null)
      return false;

    boolean this_present_paramter = true && this.isSetParamter();
    boolean that_present_paramter = true && that.isSetParamter();
    if (this_present_paramter || that_present_paramter) {
      if (!(this_present_paramter && that_present_paramter))
        return false;
      if (!this.paramter.equals(that.paramter))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(RpcResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    RpcResponse typedOther = (RpcResponse)other;

    lastComparison = Boolean.valueOf(isSetParamter()).compareTo(typedOther.isSetParamter());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParamter()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.paramter, typedOther.paramter);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RpcResponse(");
    boolean first = true;

    sb.append("paramter:");
    if (this.paramter == null) {
      sb.append("null");
    } else {
      sb.append(this.paramter);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RpcResponseStandardSchemeFactory implements SchemeFactory {
    public RpcResponseStandardScheme getScheme() {
      return new RpcResponseStandardScheme();
    }
  }

  private static class RpcResponseStandardScheme extends StandardScheme<RpcResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RpcResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PARAMTER
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.paramter = new HashMap<String,String>(2*_map0.size);
                for (int _i1 = 0; _i1 < _map0.size; ++_i1)
                {
                  String _key2; // required
                  String _val3; // required
                  _key2 = iprot.readString();
                  _val3 = iprot.readString();
                  struct.paramter.put(_key2, _val3);
                }
                iprot.readMapEnd();
              }
              struct.setParamterIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RpcResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.paramter != null) {
        oprot.writeFieldBegin(PARAMTER_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.paramter.size()));
          for (Map.Entry<String, String> _iter4 : struct.paramter.entrySet())
          {
            oprot.writeString(_iter4.getKey());
            oprot.writeString(_iter4.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RpcResponseTupleSchemeFactory implements SchemeFactory {
    public RpcResponseTupleScheme getScheme() {
      return new RpcResponseTupleScheme();
    }
  }

  private static class RpcResponseTupleScheme extends TupleScheme<RpcResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RpcResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetParamter()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetParamter()) {
        {
          oprot.writeI32(struct.paramter.size());
          for (Map.Entry<String, String> _iter5 : struct.paramter.entrySet())
          {
            oprot.writeString(_iter5.getKey());
            oprot.writeString(_iter5.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RpcResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map6 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.paramter = new HashMap<String,String>(2*_map6.size);
          for (int _i7 = 0; _i7 < _map6.size; ++_i7)
          {
            String _key8; // required
            String _val9; // required
            _key8 = iprot.readString();
            _val9 = iprot.readString();
            struct.paramter.put(_key8, _val9);
          }
        }
        struct.setParamterIsSet(true);
      }
    }
  }

}

